### ISSUE TITLE
Unable to autolaunch a dbus-daemon without a $DISPLAY for X11

### ISSUE THREAD

**Issue by l1n00** [pashazz/ksetwallpaper#5]
when i run the script with crontab i get this error in log

Traceback (most recent call last):

  File "/home/lino/ksetwallpaper/ksetwallpaper.py", line 30, in <module>
    setwallpaper(args.file, args.plugin)
  File "/home/lino/ksetwallpaper/ksetwallpaper.py", line 16, in setwallpaper
    bus = dbus.SessionBus()
  File "/usr/lib/python3/dist-packages/dbus/_dbus.py", line 213, in __new__
    mainloop=mainloop)
  File "/usr/lib/python3/dist-packages/dbus/_dbus.py", line 102, in __new__
    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 124, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NotSupported: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11

**Comment by baduhai** [comment]
My guess would be because cron runs on a different session from the user, and therefore the script can't communicate with the need dbus session. This is not exactly a problem with this script as it is with running this script with cron.
